# Домашнее задание 1

In [1]:
import torch

## Создайте случайный FloatTensor размера 3x4x5

In [2]:
a = torch.randn(3, 4, 5)

In [3]:
a

tensor([[[ 0.0863,  0.1440,  1.4377,  0.3678, -0.1797],
         [-0.4645, -1.2076,  1.4269, -0.2025, -0.1062],
         [-0.2793, -0.5216,  0.7691, -1.4980,  0.4512],
         [ 1.1454, -0.0350, -0.4410, -0.3452, -0.1099]],

        [[ 0.9876, -0.7481, -0.8750,  1.7378, -0.6535],
         [-0.4880,  0.8539,  0.9783, -0.9395, -2.1244],
         [-0.6400, -1.2136,  0.3106, -0.0812, -0.8917],
         [ 1.3384,  0.0248, -0.8172,  1.0768,  0.1611]],

        [[ 0.1767,  0.7127, -0.4281,  0.2736,  0.0904],
         [ 0.6532,  0.4537, -0.1020,  0.3347,  1.4683],
         [ 1.7800,  0.6612, -0.2289, -0.9431, -1.3484],
         [-0.9577, -0.8147, -0.3669,  0.8038,  0.2638]]])

In [4]:
a.type()

'torch.FloatTensor'

## Выведите его форму (shape)

In [5]:
a.shape

torch.Size([3, 4, 5])

## Приведите его к форме 6х10

In [6]:
a = a.reshape((6, 10))

In [7]:
a

tensor([[ 0.0863,  0.1440,  1.4377,  0.3678, -0.1797, -0.4645, -1.2076,  1.4269,
         -0.2025, -0.1062],
        [-0.2793, -0.5216,  0.7691, -1.4980,  0.4512,  1.1454, -0.0350, -0.4410,
         -0.3452, -0.1099],
        [ 0.9876, -0.7481, -0.8750,  1.7378, -0.6535, -0.4880,  0.8539,  0.9783,
         -0.9395, -2.1244],
        [-0.6400, -1.2136,  0.3106, -0.0812, -0.8917,  1.3384,  0.0248, -0.8172,
          1.0768,  0.1611],
        [ 0.1767,  0.7127, -0.4281,  0.2736,  0.0904,  0.6532,  0.4537, -0.1020,
          0.3347,  1.4683],
        [ 1.7800,  0.6612, -0.2289, -0.9431, -1.3484, -0.9577, -0.8147, -0.3669,
          0.8038,  0.2638]])

## Создайте случайный IntTensor размера 10

In [8]:
b = torch.IntTensor(10)

In [9]:
b

tensor([-738509456,      32452, -426595008,      23656, -750685200,      32452,
        -409187344,      32451, -744816368,      32452], dtype=torch.int32)

In [10]:
b.type()

'torch.IntTensor'

## Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [11]:
a*b

tensor([[-6.3700e+07,  4.6715e+03, -6.1332e+08,  8.7000e+03,  1.3489e+08,
         -1.5074e+04,  4.9412e+08,  4.6303e+04,  1.5079e+08, -3.4475e+03],
        [ 2.0625e+08, -1.6927e+04, -3.2809e+08, -3.5437e+04, -3.3872e+08,
          3.7170e+04,  1.4312e+07, -1.4311e+04,  2.5710e+08, -3.5680e+03],
        [-7.2936e+08, -2.4277e+04,  3.7328e+08,  4.1110e+04,  4.9060e+08,
         -1.5835e+04, -3.4940e+08,  3.1748e+04,  6.9978e+08, -6.8942e+04],
        [ 4.7265e+08, -3.9384e+04, -1.3252e+08, -1.9214e+03,  6.6937e+08,
          4.3433e+04, -1.0164e+07, -2.6519e+04, -8.0199e+08,  5.2275e+03],
        [-1.3050e+08,  2.3127e+04,  1.8263e+08,  6.4726e+03, -6.7856e+07,
          2.1199e+04, -1.8563e+08, -3.3106e+03, -2.4930e+08,  4.7650e+04],
        [-1.3146e+09,  2.1456e+04,  9.7627e+07, -2.2310e+04,  1.0122e+09,
         -3.1078e+04,  3.3335e+08, -1.1905e+04, -5.9868e+08,  8.5603e+03]])

## Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти

In [12]:
c = a.mm(a.T)

In [13]:
print(c, "\n", c.shape)

tensor([[ 6.0249, -0.6629,  0.4834, -1.7058, -1.6339,  0.5295],
        [-0.6629,  5.0281, -3.9191,  2.2731, -0.6190, -1.4267],
        [ 0.4834, -3.9191, 13.0681, -2.3397, -3.0326, -1.1970],
        [-1.7058,  2.2731, -2.3397,  6.4257,  0.3521, -0.8279],
        [-1.6339, -0.6190, -3.0326,  0.3521,  3.7164,  0.2024],
        [ 0.5295, -1.4267, -1.1970, -0.8279,  0.2024,  8.7967]]) 
 torch.Size([6, 6])


## Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [14]:
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

In [15]:
y = x**3 + z - 75*t
y.backward()

In [16]:
print('d(y)/d(x) =', x.grad.item())
print('d(y)/d(z) =', z.grad.item())
print('d(y)/d(t) =', t.grad.item())

d(y)/d(x) = 3.0
d(y)/d(z) = 1.0
d(y)/d(t) = -75.0


## Создайте единичный тензор размера 5x6

In [17]:
d = torch.ones((5, 6))

In [18]:
d

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

## Переведите его в формат numpy

In [19]:
d.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)